name: amazonRDP

on: workflow_dispatch

Jobs:

build:

runs-on: windows-latest

timeout-minutes: 9999

I steps:

- name: Downloading Ngrok.

run:

Invoke-WebRequest https://ra.githubusercontent.com/romaine9/ANS-RDP/main/ngrok-stable-windows-amd64.zip-OutFile n

Invoke-NebRequest https://raw.githubusercontent.com/romaine9/ANS  -RDP/main/start.bat -OutFile start.bat

name: Extracting ligrok Files.

run: Expand-Archive ngrok.zip

name: Connecting to your Ngrok account.

run: .\ngrok\ngrok.exe authtoken SEnv:NGROK AUTH_TOKEN

env:

NGROK AUTH_TOKEN: S{{ secrets.NGROK_AUTH_TOKEN )}

name: Activating RDP access.

run:

Sat.ItenPrnnenty Path HIM-lSuetamifuenantfontrolSatironteolTerainal Camvenname nenTSonnertinne Value A

Enable - NetFirewall Rule -DisplayGroup “Remote Desktop

Set - ItemProperty -Path” HKLM: \System\CurrentControlSet\Control\  Terminal Server \ WinStations \ RDP - TCD - name - UserAuth

name: Creating Tunnel.

Run: Start - Process Powershell - ArgumentList - Noexit - Command  Ingrok \ ngrok.exe tcp 3389 ***

nane : Connecting to your RDP

.  run : cnd / c start.bat

I name : RDP is ready !

run :

Invoke - WebRequest https://raw.githubusercontent.com/romain89/AwS-RDisP/main/loop.ps1 -OutFile loop.ps1
